version: '3.7'

networks:
  influx:
    driver: bridge

services:

  ##########################################
  # Datastore
  ##########################################
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    # needs a network for a container to perform backups
    networks:
      - influx
    ports:
      - "8086:8086"
      - "8088:8088"
    volumes:
      - /mnt/influx:/var/lib/inflxdb

  ##########################################
  # API's
  ##########################################
  auth-api:
    build:
      context: .
      dockerfile: "./auth_docker"
    networks:
      - influx
    depends_on:
      - influxdb
    # expose:
    #   - "5001"
   ports:
    - "5001:5001"
  sensor-api:
    build:
      context: .
      dockerfile: "./sensor_docker"
    networks:
      - influx
    restart: unless-stopped
    depends_on:
      - influxdb
    # expose:
    #   - "5002"
    ports:
      - "5002:5002"

#  door-api:
#    build:
#      context: .
#      dockerfile: "./door_docker"
#    restart: unless-stopped
#    ports:
#      - "5003:5003"

# volumes:
#   sqlite_db:
#   influx:
