version: '3.7'

# connect to pre-esisting network. if not created create by:
# docker network create vexme
networks:
  vexme:
    external:
      name: vexme

# networks:
#   influx:
#     driver: bridge

services:

  ##########################################
  # Datastore
  ##########################################
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    # needs a network for a container to perform backups
    networks:
      - vexme
    # determine if we need to expose influxdb to host or
    # can keep in dodker network
    # expose:
    #   - "8088"
    #   - "8086"
    # following exposes ports to host
    ports:
      - "8086:8086"
      - "8088:8088"
    volumes:
      - /mnt/influx:/var/lib/inflxdb

  ##########################################
  # Grafana for visualisatons
  ##########################################
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    networks:
      - vexme
    environment:
      GF_SERVER_ROOT_URL: http://grafana/api/grafana
    expose:
      - "3000"
    # https://grafana.com/docs/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
    # user: "104"
    # volumes:
    #   - /mnt/kong/grafana:/var/lib/grafana


  ##########################################
  # API's
  ##########################################
  auth-api:
    build:
      context: .
      dockerfile: "./auth_docker"
    networks:
      - vexme
    depends_on:
      - influxdb
    expose:
      - "5001"
    # ports:
    #   - "5001:5001"
  sensor-api:
    build:
      context: .
      dockerfile: "./sensor_docker"
    networks:
      - vexme
    restart: unless-stopped
    depends_on:
      - influxdb
    expose:
      - "5002"
    # ports:
    #   - "5002:5002"

#  door-api:
#    build:
#      context: .
#      dockerfile: "./door_docker"
#    restart: unless-stopped
#    ports:
#      - "5003:5003"

# volumes:
#   sqlite_db:
#   influx:
