#!/bin/bash

# configure SELinux to allow ports
#Auth
semanage port -a -t http_port_t -p tcp 5006
# Senosrs
semanage port -a -t http_port_t -p tcp 5007
#  Tanks
semanage port -a -t http_port_t -p tcp 5008
#Grafana
semanage port -a -t http_port_t -p tcp 3000
# Influx?
semanage port -a -t http_port_t -p tcp 8086

# Need to add services for routes after fresh kong install

# Tanks service

curl -i -X POST \
    --url http://localhost:8001/services/ \
    --data 'name=tanks' \
    --data 'url=http://tank-ingress-api:5008'

#tanks route

curl -i -X POST http://localhost:8001/services/tanks/routes \
    --data 'paths[]=/marcus' \
    --data name=tank-route \
    --data service=tanks \
    --data strip_path=false

#grafana

curl -i -X POST \
    --url http://localhost:8001/services/ \
    --data 'name=grafana' \
    --data 'url=http://grafana:3000'

curl -i -X POST http://localhost:8001/services/grafana/routes \
    --data 'paths[]=/grafana' \
    --data name=grafana-route \
    --data service=grafana
